version: "3.8" # version is obsolete in 2026

services:

  api:
    image: krishna4372/fastapi
    depends_on:
        - postgres
    ports:
      # - <port on localhost>:<port on container>
      - 80:8000
    
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 # changes commands from dockerfile

    environment:
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # results to postgres IP address by itself
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      

    volumes:
        - postgres-db:/var/lib/postgresql

volumes:
    postgres-db: